name: Sync

on:
  push:
    branches: [main]
    paths-ignore:
      - "*.md"
  schedule:
    - cron: "0 20 25 * *" # 毎月26日 05:00 JST
  workflow_dispatch:

concurrency:
  group: sync
  cancel-in-progress: false

jobs:
  sync:
    uses: queria-io/dataset-shared/.github/workflows/sync.yml@main
    with:
      dataset_name: opendata_census
    secrets: inherit
